### ISSUE TITLE
To-do overview

### ISSUE THREAD

**Issue by MizzleDK** [MizzleDK/Mizuu-Android-TV#1]
**WORK IN PROGRESS**

This new version should be published in a new branch.
### Movies
- [ ] ...
### TV shows
- [ ] ...
### Video files
- [ ] If a file cannot be identified as either a TV show or movie, it'll show up in "Video files"
### Library overviews
- [ ] Search
- [ ] Filtering
- [ ] Sorting
- [ ] Sections, i.e. "All movies" and "Favourites" (from right-side drawer)
- [ ] Random selection
### File sources
- [ ] DLNA
### Library update options
- [ ] Clear library
- [ ] Refresh library data
- [ ] Remove unavailable files
### File recognition
- [ ] Automatic detection of whether a file is a movie, TV show episode or other video file
### Trakt synchronization (v2 API)
- [ ] OAuth
- [ ] More...
### Settings
- [ ] Preferred language for movies and TV shows
- [ ] Ignored filename tags
- [ ] File size limits
- [ ] Scheduled library updates
- [ ] Show file paths in detail views
### Database
- [ ] SQLite
### Video playback
- [ ] Intent extras, i.e. title, meta data and subtitle url
